name: cibo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.1
  intl: any
  meta: ^1.16.0
  objectbox: ^5.1.0
  objectbox_flutter_libs: any
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  objectbox_generator: any

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/Images/

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: objectbox
  # Or optionally specify the lib and test output folder separately.
  # output_dir:
  #   lib: custom
  #   test: other

